export XDG_DOCUMENTS_DIR="$HOME/documents/"
export PULSE_COOKIE="$HOME/.config/pulse-cookie"
export XAUTHORITY="$HOME/.config/Xauthority"
export PATH="$HOME/.local/bin:$PATH"

[[ $- != *i* ]] && return

export PS1="\[\e[34m\]\w\[\e[m\]$ "
export BROWSER=firefox
export EDITOR=nvim
export HISTFILE=~/.config/.bash_history
export HISTFILESIZE=100000

alias ls='ls --color=auto'
alias windows='sudo efibootmgr -n 0002 && reboot'
