[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias update='sudo pacman -Syu'
alias hfzf='$(sort -u ~/.bash_history | fzf)'

export PATH="$HOME/.local/bin:$PATH"

XDG_DOCUMENTS_DIR="$HOME/documents/"
XDG_DOWNLOAD_DIR="$HOME/downloads/"

PS1="\[\e[34m\]\w\[\e[m\]$ "

export EDITOR=nvim
