export XDG_DOCUMENTS_DIR="$HOME/documents/"
export XDG_CACHE_HOME="$HOME/.local/cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export _JAVA_OPTIONS="-Djava.util.prefs.userRoot=$XDG_CONFIG_HOME/java"
export PATH_TO_FX="$XDG_DATA_HOME/openjfx"
export SSL_CERT_DIR="$XDG_CONFIG_HOME/pki"
export SSL_CERT_FILE="$XDG_CONFIG_HOME/pki/ca-bundle.crt"
export PULSE_COOKIE=$HOME/.config/pulse-cookie
export XAUTHORITY=$HOME/.config/Xauthority

[[ $- != *i* ]] && return

HISTFILE=~/.config/.bash_history
HISTSIZE=100000
HISTFILESIZE=200000

PS1="\[\e[34m\]\w\[\e[m\]$ "
alias ls='ls --color=auto'
alias windows='sudo efibootmgr -n 0002 && reboot'

export BROWSER=firefox
export EDITOR=nvim
export vim=nvim
export DISCORD_DISABLE_RPC=1
export PATH="$HOME/.local/bin:$PATH"

# ---

mars() {
  java -jar "$HOME/.local/java/Mars4_5.jar" "$@"
}
